part12-containers-applications/my-app/src/models/messaging_models.py
from flask_sqlalchemy import SQLAlchemy
from src.__init__ import app
message_db = SQLAlchemy(app)


class MessageManager():
    def __init__(self, sender=None, receiver="admin", message_id=None, message=None, tag="normal"):
        self.sender = sender
        self.receiver = receiver
        self.message = message
        self.message_id = message_id
        self.tag = tag

    def insert_message(self):
        sql = """INSERT INTO messages (sender, receiver, message, tag)
        VALUES (:sender, :receiver, :message, :tag);"""
        message_db.session.execute(
            sql, {"sender": self.sender,
                  "receiver": self.receiver,
                  "message": self.message,
                  "tag": self.tag})
        message_db.session.commit()

    def fetch_messages(self):
        sql = """(SELECT id, sender, receiver, message, creation_date
        FROM messages
        WHERE sender=:sender AND  receiver=:receiver AND tag='normal')
        UNION ALL (
            SELECT id, sender, receiver, message, creation_date
            FROM messages WHERE sender=:receiver AND receiver=:sender AND tag='normal')
        ORDER BY creation_date ASC;"""
        data = message_db.session.execute(sql, {"sender": self.sender,
                                                "receiver": self.receiver}).fetchall()
        message_db.session.commit()
        return data

    def fetch_report_messages(self):
        sql = """SELECT id, sender, receiver, message, creation_date
        FROM messages
        WHERE tag='report'
        ORDER BY creation_date ASC;"""
        data = message_db.session.execute(sql).fetchall()
        return data

    def delete_messages(self):
        sql = """DELETE FROM messages
        WHERE receiver=:receiver AND sender=:sender;"""
        message_db.session.execute(sql, {"receiver": self.receiver,
                                         "sender": self.sender})
        message_db.session.commit()

    def fetch_senders(self):
        sql = """SELECT COUNT(id), sender
        FROM messages
        WHERE receiver=:receiver
        GROUP BY sender;"""
        data = message_db.session.execute(
            sql, {"receiver": self.receiver}).fetchall()
        if data:
            return data
        return None

    def fetch_receivers(self):
        sql = """SELECT COUNT(id), receiver
        FROM messages WHERE sender=:sender
        GROUP BY receiver;"""
        data = message_db.session.execute(
            sql, {"sender": self.sender}).fetchall()
        if data:
            return data
        return None

    def delete_message(self):
        sql = "DELETE FROM messages WHERE id=:id;"
        message_db.session.execute(sql, {"id": self.message_id})
        message_db.session.commit()

    def update_tag(self, tag):
        sql = "UPDATE messages SET tag=:tag WHERE id=:message_id;"
        message_db.session.execute(
            sql, {"tag": tag, "message_id": self.message_id})
        message_db.session.commit()


class CommentManager():
    def __init__(self, comment=None, product_id=None, comment_id=None, username=None):
        self.comment = comment
        self.product_id = product_id
        self.comment_id = comment_id
        self.commentor_username = username

    def insert_comments(self):
        sql = """INSERT INTO comments (user_comment, product_id, commentor_username)
        VALUES (:user_comment, :product_id, :commentor_username); """
        message_db.session.execute(sql, {"user_comment": self.comment,
                                         "product_id": self.product_id,
                                         "commentor_username": self.commentor_username})
        message_db.session.commit()

    def fetch_comments(self):
        sql = """SELECT id, user_comment, product_id, commentor_username, creation_date
        FROM comments WHERE product_id=:product_id
        ORDER BY creation_date DESC;"""
        return message_db.session.execute(sql, {"product_id": self.product_id}).fetchall()

    def delete_comment(self):
        sql = """DELETE FROM comments
        WHERE id=:comment_id;"""
        message_db.session.execute(sql, {"comment_id": self.comment_id})
        message_db.session.commit()


def count_messages(sender, receiver):
    sql = """SELECT count(id) FROM messages
    WHERE (sender=:sender and receiver=:receiver)
    OR (receiver=:sender and sender=:receiver);"""
    message_count = message_db.session.execute(
        sql, {"sender": sender, "receiver": receiver}).fetchone()
    return message_count[0]

part12-containers-applications/my-app/src/forms/messaging_form.py
from flask_wtf import FlaskForm
from wtforms import(
    StringField,
    validators,
    ValidationError,
    TextAreaField)

from flask_login import current_user
from markupsafe import Markup
from src.models.messaging_models import MessageManager
from src.models.user_model import check_username

class MessageForm(FlaskForm):
    sender = StringField("sender", [validators.Length(
        min=4, max=40),
        validators.Email(message="Username format is incorrect."),
        validators.DataRequired()])
    receiver = StringField("receiver", [
        validators.Length(min=4, max=40),
        validators.Email(message="Username format is incorrect."),
        validators.DataRequired()])
    message = TextAreaField("message",
                            [validators.Length(min=0),
                             validators.DataRequired()])

    def validate_receiver(self, receiver):
        username_exists = check_username(receiver)
        if not username_exists:
            raise ValidationError("Username doesn't exist")

    def validate_sender(self, sender):
        username = current_user.username
        if sender == username:
            raise ValidationError("You can't send message to yourself.")

    def send_message(self, sender, receiver, message):
        if receiver != sender:
            message = MessageManager(
                sender=sender, receiver=receiver, message=message)
            message.insert_message()
            return True
        return False

    def send_report(self, sender, message):
        message = MessageManager(sender=sender, message=message, tag="report")
        message.insert_message()


class CommentReportForm(FlaskForm):
    sender = StringField("sender", [validators.Length(
        min=4, max=40), validators.DataRequired()])
    reported = StringField("reported", [validators.Length(
        min=4, max=40), validators.DataRequired()])
    product_id = StringField("product_id", [validators.Length(
        min=4, max=40), validators.DataRequired()])
    comment_id = StringField("comment_id", [validators.Length(
        min=4, max=40), validators.DataRequired()])
    comment = StringField("comment", [validators.Length(
        min=0, max=350), validators.DataRequired()])
    message = TextAreaField("message", [validators.Length(
        min=0), validators.DataRequired()])

    def validate_reported(self, reported):
        username_exists = check_username(reported)
        if not username_exists:
            raise ValidationError(
                Markup("Username doesn't exist"))

    def validate_sender(self, sender):
        username = current_user.username
        if sender == username:
            raise ValidationError("You can't send message to yourself.")

    def send_report(self, sender, message):
        message = MessageManager(sender=sender, message=message, tag="report")
        message.insert_message()

part12-containers-applications/my-app/src/views.py
import json
from uuid import uuid4
from os import remove, path
import click
from werkzeug.utils import secure_filename
from werkzeug.middleware.proxy_fix import ProxyFix
from werkzeug.security import generate_password_hash
from flask import Blueprint, render_template, redirect, flash, url_for, request, abort
from flask_login import current_user, login_required, login_user, logout_user
from flask_wtf.csrf import CSRFProtect
from flask_sqlalchemy import SQLAlchemy
from src.__init__ import app, login_manager
from src.forms.messaging_form import (
    MessageForm,
    CommentReportForm
)
from src.forms.login_form import LoginForm
from src.forms.registration_form import (RegistrationForm, ProfileForm)
from src.models.user_model import(
    UserManager,
    ProfileManager,
    User,
    check_username
)
from src.models.product_models import(
    FilterManager,
    ProductManager,
    check_product_exists,
    delete_product,
    delete_product_images,
    fetch_issold,
    fetch_product_imgs,
    fetch_product_img,
    fetch_product,
    fetch_bought_products,
    fetch_sold_products,
    fetch_user_products,
    update_issold,
    count_sold_products
)
from src.models.messaging_models import CommentManager, MessageManager, count_messages
from src.forms.password_change_form import PasswordChangeForm
db = SQLAlchemy(app)
login_manager.init_app(app)
csrf = CSRFProtect(app)
app.wsgi_app = ProxyFix(app.wsgi_app)


@app.cli.command("create-admin")
@click.argument("username")
@click.argument("password")
def create_admin(username, password):
    password_hash = generate_password_hash(password)
    user = UserManager(username=username)
    registration_info = {
        "username": None,
        "password": password_hash,
        "first_name": None,
        "email": str(uuid4())+"@admin.admin",
        "last_name": None,
        "street_address": None,
        "phone_number": 000000000,
        "country": None,
        "city": None,
        "province": None,
        "postal_code": None,
        "birthday": None,
        "profile_picture_id": "default.png"
    }
    user.create_user(registration_info)
    user.update_is_admin(True)


ALLOWED_PROFILE_EXTENSIONS = set(['png', 'jpg', 'jpeg', 'gif'])


def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_PROFILE_EXTENSIONS


filter_manager = FilterManager()
views = Blueprint("views", __name__)


@login_manager.user_loader
def user_loader(user_id):
    return User.get(current_user, user_id=user_id)


@views.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("views.home"))
    form = LoginForm()

    if form.validate_on_submit():

        user = UserManager(username=form.username.data).fetch_user()
        login_user(user, remember=True)
        user.create_session(user)
        if not current_user.is_active:
            flash("You can't access this page since you have been banned.")
        return redirect(url_for("views.home"))
    return render_template("/login.html", form=form)


@views.route("/logout")
@login_required
def logout():
    current_user.delete_session()
    logout_user()
    flash("You have logged out.", category="success")
    return redirect(url_for("views.login"))


@views.route("/signup", methods=["GET", "POST"])
@views.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        password_hash = generate_password_hash(form.password.data)
        user = UserManager(username=form.username.data)
        registration_info = {
            "username": form.username.data,
            "password": password_hash,
            "first_name": form.first_name.data,
            "email": form.email.data,
            "last_name": form.last_name.data,
            "street_address": form.street_address.data,
            "phone_number": form.phone_number.data,
            "country": form.country.data,
            "city": form.city.data,
            "province": form.province.data,
            "postal_code": form.postal_code.data,
            "birthday": form.birthday.data,
            "profile_picture_id": "default.png",
            "admin": False
        }
        user = user.create_user(registration_info)
        if user:
            user.create_session(user)
            login_user(user, remember=True)
            flash("Congratulations, your registration is complete.",
                  category="success")
            return redirect(url_for("views.home"))
        flash("Something went wrong with registration, please try again.")
    return render_template("/register.html", form=form)


@app.context_processor
def post_injection():
    return dict(
        message_form=MessageForm(),
        profile_form=ProfileForm(),
        password_change_form=PasswordChangeForm(),
        report_form=CommentReportForm(),
        message_manager=MessageManager,
        profile_manager=ProfileManager(),
        user_manager=UserManager,
        filter_manager=FilterManager(),
        get_profile_picture=ProfileManager().get_profile_picture,
        fetch_issold=fetch_issold,
        fetch_product_imgs=fetch_product_imgs,
        fetch_product_img=fetch_product_img,
        fetch_product=fetch_product,
        fetch_profile_picture=ProfileManager().fetch_profile_picture,
        check_product_exists=check_product_exists,
        fetch_bought_products=fetch_bought_products,
        fetch_sold_products=fetch_sold_products,
        fetch_user_products=fetch_user_products,
        count_sold_products=count_sold_products,
        count_messages=count_messages
    )


@views.route("/", methods=["GET", "POST"])
@views.route("/home", methods=["GET", "POST"])
def home():
    if current_user.is_anonymous:
        return render_template("index.html")
    return render_template("index.html", name=current_user.first_name)


@views.route("/marketplace", methods=["GET"])
@views.route("/market", methods=["GET"])
@login_required
def marketplace():
    products = filter_manager.fetch_products()
    return render_template("marketplace.html", products=products)


@views.route("/set_condition/<condition>")
@login_required
def set_condition(condition):
    filter_manager.set_condition(condition)
    return redirect(url_for("views.marketplace"))


@views.route("/set_category/<category>")
@login_required
def set_category(category):
    filter_manager.set_category(category)
    return redirect(url_for("views.marketplace"))


@views.route("/set_sort/<sort>")
@login_required
def set_sort(sort):
    filter_manager.set_sort(sort)
    return redirect(url_for("views.marketplace"))


@views.route("/set_search")
@login_required
def set_search():
    search = request.args["search"]
    filter_manager.set_search(search)
    return redirect(url_for("views.marketplace"))


@views.route("/marketplace", methods=["POST"])
@views.route("/market", methods=["POST"])
@login_required
def product_add():
    if request.method == "POST":
        data = request.files.getlist("product_pictures")
        product_info = {"title": request.form["title"],
                        "details": request.form["details"],
                        "price": request.form["price"],
                        "category": request.form["category"],
                        "condition": request.form["condition"]}
        product_id = str(uuid4())
        new_product = ProductManager(product_id=product_id,
                                     username=current_user.username)
        new_product.set_product_info(product_info=product_info)
        new_product.insert_product()
        for file in data:
            if file and allowed_file(file.filename):
                filename = str(uuid4())
                file_extension = file.filename.rsplit('.', 1)[1].lower()
                file.filename = filename+"."+file_extension
                secured_filename = secure_filename(file.filename)
                file.save(path.join(app.root_path+
                          "/static/images/"+secured_filename))
                new_product.insert_product_imgs(img_id=secured_filename)
            else:
                flash("Acceptable extensions are: png, jpg, jpeg and gif.")
                return redirect(request.url)
    return redirect(url_for("views.marketplace"))


@views.route("/product/<product_id>", methods=["GET"])
@login_required
def product(product_id):
    comments = CommentManager(product_id=product_id).fetch_comments()
    return render_template("product.html",
                           product_id=product_id,
                           comments=comments)


@views.route("/product_delete/<product_id>", methods=["GET"])
@login_required
def product_delete(product_id):
    imgs = fetch_product_imgs(product_id)
    if imgs is not None:
        for img in imgs:
            if path.exists(app.root_path+"/static/images/"+img[0]):
                remove(path.join(app.root_path+"/static/images/"+img[0]))
    delete_product(product_id)
    return redirect(url_for("views.marketplace"))


@views.route("/product/<product_id>/<comment_id>", methods=["GET"])
@login_required
def comment_delete(product_id, comment_id):
    CommentManager(comment_id=comment_id).delete_comment()
    comments = CommentManager(product_id=product_id).fetch_comments()
    return render_template("product.html",
                           product_id=product_id,
                           comments=comments
                           )


@views.route("/product/<product_id>/comment", methods=["POST"])
@login_required
def comment(product_id):
    if request.method == "POST":
        new_comment = request.form["comment"]
        mgr = CommentManager(
            comment=new_comment,
            product_id=product_id,
            username=current_user.username
        )
        mgr.insert_comments()
        comments = CommentManager(product_id=product_id).fetch_comments()
        return redirect(url_for("views.product",

part12-containers-applications/my-app/src/templates/about.html
{% extends "base.html" %}
{% block head %}
{% endblock %}
{% block body %}
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <main class="px-3" style="height:800px">
        <div class="jumbotron">
            <h1 class="display-4">About.</h1>
            <p class="lead">This is a place where dreams come true. This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. This is a place where dreams come true.
                This is a place where dreams come true. This is a
                place where dreams come true. This is a place where dreams come true This is a place where dreams come
                true. This is a place where dreams come true This is a place where dreams come true. This is a place
                where dreams come true. This is a place where dreams come true. </p>
            © 2022 Copyright: <a class="text-black">Marketplace</a>
        </div>
    </main>
</div>
{% endblock %}

part12-containers-applications/my-app/src/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous" />
    <link href='https://fonts.googleapis.com/css?family=Gruppo' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        body {
            font-size: 12px;
        }
    </style>
    {% block head%}{% endblock head%}
</head>

<body>
    <link rel="stylesheet" type="text/css" href="{{url_for('static',filename='styles/main.css')}}">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js"
        integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk"
        crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js"
        integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy"
        crossorigin="anonymous"></script>

    <div class="container-fluid" style="background-color: #b6dff3">
        <header
            class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-4 mb-4 ">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

                    <a {% if current_user.is_anonymous %} href="{{ url_for('views.home') }}" {% else %}
                        href="{{ url_for('views.marketplace') }}" {% endif %}
                        class="d-flex align-items-center col-md-3 mb-2 text-dark text-decoration-none">
                        <h1>AstraMarket</h1>
                    </a>

                    {% if current_user.is_authenticated %}
                    <ul class="nav col-15 mb-2 justify-content-end mb-md-0">
                        <li class="nav-item w3-bar-item">
                            <h5><a href="{{ url_for('views.home') }}" class="nav-link w3-button w3-bar-item"
                                    style="color:#030e12;"> Home </a>
                            </h5>
                        </li>

                        <li class="nav-item w3-bar-itemm">
                            <h5><a href="{{url_for('views.profile',username=current_user.username) }}"
                                    class="nav-link w3-button w3-bar-item" style="color:#030e12"> Profile
                                </a></h5>
                        </li>
                        <li>
                            <h5><a href="{{ url_for('views.send_message') }}" class="nav-link w3-button w3-bar-item"
                                    data-bs-toggle="modal" data-bs-target="#message-user" style="color:#030e12"> Send a
                                    message
                                </a></h5>
                        </li>
                        <li class="nav-item w3-bar-itemm">
                            <h5><a href="{{ url_for('views.logout') }}" class="nav-link w3-button w3-bar-item"
                                    style="color:#030e12"> Log out
                                </a></h5>
                        </li>
                    </ul>
                    {% else %}
                    <div class="nav col-15 md-5 justify-content-end">
                        <h5><a href="{{ url_for('views.login') }}" class="nav-link w3-button w3-bar-item"
                                style="color:#030e12"> Log In
                            </a></h5>
                        <h5><a href="{{ url_for('views.register') }}" class="nav-link w3-button w3-bar-item"
                                style="color:#030e12"> Sign Up
                            </a></h5>
                    </div>
                    <div class="nav col-15 md-5 justify-content-end">
                        <h5><a href="{{ url_for('views.about') }}" class="nav-link w3-button w3-bar-item"
                                style="color:#030e12"> About us
                            </a></h5>
                    </div>
                    {% endif %}
                    {% if current_user.is_admin %} 
                    <div class="nav col-15 md-5 justify-content-end">
                        <h5><a href="{{ url_for('views.admin') }}" class="nav-link w3-button w3-bar-item"
                                style="color:#030e12"> Admin page
                            </a></h5>
                    </div>
                    {% endif %}
                    <div class="modal fade" tabindex="-1" id="message-user">
                        <div class="modal-dialog">
                            <div class="modal-content" role="">
                                <div class="modal-header" style="background-color:rgb(175, 223, 235);">
                                    <h5 class="modal-title">Send a message:</h5>
                                </div>
                                <div class="modal-body">
                                    <form action="{{url_for('views.send_message', username=current_user.username)}}"
                                        method="POST">
                                        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
                                        <br>
                                        <div class="form-floating">
                                            {{message_form.receiver(class="form-control border-1 shadow-m",type="text",
                                            id="receiver",placeholder="")}}
                                            <label for="receiver">username / message to :</label>
                                        </div>
                                        <br>
                                        {{ message_form.sender(class="form-control",type="hidden", id="sender",
                                        value=current_user.username)}}
                                        <div class="form-floating">
                                            {{ message_form.message(class="form-control border-2 shadow-m", type="text",
                                            id="message", minlength="4", placeholder="Your message here:")}}
                                            <label for="message">Your message here:</label>
                                        </div>
                                        <br>
                                        <div class="modal-footer">
                                            <button type="submit" class="btn close btn-primary">Submit</button>
                                            <a href="{{url_request}}"><button type="button" class="btn close btn-danger"
                                                    data-bs-dismiss="modal">Cancel</button></a>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
    </div>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block body %}{% endblock body %}
</body>

</html>